/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Report;

import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import DBUtils.TblBill;

/**
 *
 * @author ASUS
 */
public class displaySaleReport extends javax.swing.JFrame {

    /**
     * Creates new form displaySaleREport
     */
    public displaySaleReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblsalrep = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        cbxUser = new javax.swing.JComboBox<>();
        cbxDate = new javax.swing.JComboBox<>();
        btnFilter = new javax.swing.JButton();
        cbxLanguage = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblsalrep.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblsalrep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsalrep.setText("SALE REPORT");

        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBill);

        cbxUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnFilter.setText("Filter");
        btnFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFilterMouseClicked(evt);
            }
        });

        cbxLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EN", "VN" }));
        cbxLanguage.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLanguageItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblsalrep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxUser, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(btnFilter)
                        .addGap(116, 116, 116)
                        .addComponent(cbxDate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblsalrep, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        TblBill exc = new TblBill();
        tblBill.setModel(exc.loadBillTable());
        loadComboBox();
    }//GEN-LAST:event_formWindowActivated

    private void btnFilterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFilterMouseClicked
        filterRowsByUser();
        filterRowsByDate();
    }//GEN-LAST:event_btnFilterMouseClicked

    private void cbxLanguageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLanguageItemStateChanged
        Locale loc;

        if (cbxLanguage.getSelectedItem().equals("VN")) {
            loc = new Locale("vi", "VN");
            changeLanguageTo(loc);
        } else {
            loc = new Locale("en", "US");
            changeLanguageTo(loc);
        }
    }//GEN-LAST:event_cbxLanguageItemStateChanged

    public void changeLanguageTo(Locale loc) {
        ResourceBundle rb = ResourceBundle.getBundle("pkgLanguage/MessageBundle", loc);
        lblsalrep.setText(rb.getString("salrep"));
    }
    
    public void loadComboBox() {
        loadCbxUser();
        loadCbxDate();
    }
    
    public void loadCbxUser() {
        cbxUser.removeAllItems();
        cbxUser.addItem("All");
        for (int i = 0; i < tblBill.getRowCount(); i++) {
            String temp = tblBill.getValueAt(i, 0).toString();
            boolean flat = true;
            for (int j = 0; j < cbxUser.getItemCount(); j++) {
                if (temp.equals(cbxUser.getItemAt(j))) {
                    flat = false; break;
                }
            }
            if (flat) cbxUser.addItem(tblBill.getValueAt(i, 0).toString());
        }
    }
    
    public void loadCbxDate() {
        cbxDate.removeAllItems();
        cbxDate.addItem("All");
        for (int i = 0; i < tblBill.getRowCount(); i++) {
            String temp = tblBill.getValueAt(i, 3).toString();
            boolean flat = true;
            for (int j = 0; j < cbxDate.getItemCount(); j++) {
                if (temp.equals(cbxDate.getItemAt(j))) {
                    flat = false; break;
                }
            }
            if (flat) cbxDate.addItem(tblBill.getValueAt(i, 3).toString());
        }  
    }
    
    private void filterRowsByUser() {
        DefaultTableModel tblModel = new TblBill().loadBillTable();
        Vector data = new Vector();
        String item = cbxUser.getSelectedItem().toString();
        if (!item.equals("All")) {
            int rowCount = tblModel.getRowCount();
            int colCount = tblModel.getColumnCount();

            for (int i = 0; i < rowCount; i++) {
                if (tblModel.getValueAt(i, 0).toString().trim().equals(item)) {
                    Vector rowData = new Vector();
                    for (int j = 0; j < colCount; j++) {
                        rowData.add(tblModel.getValueAt(i, j));
                    }
                    data.add(rowData);
                }
            }
            Vector tableTitle = new Vector();
            for (int i = 0; i < colCount; i++) {
                tableTitle.add(tblBill.getColumnName(i));
            }
            
            tblModel.setDataVector(data, tableTitle);
        } 
        tblBill.setModel(tblModel);
    }
    
    private void filterRowsByDate() {
        DefaultTableModel tblModel = (DefaultTableModel) tblBill.getModel();
        Vector data = new Vector();
        String item = cbxDate.getSelectedItem().toString();
        if (!item.equals("All")) {
            int rowCount = tblModel.getRowCount();
            int colCount = tblModel.getColumnCount();

            for (int i = 0; i < rowCount; i++) {
                if (tblModel.getValueAt(i, 3).toString().trim().equals(item)) {
                    Vector rowData = new Vector();
                    for (int j = 0; j < colCount; j++) {
                        rowData.add(tblModel.getValueAt(i, j));
                    }
                    data.add(rowData);
                }
            }
            Vector tableTitle = new Vector();
            for (int i = 0; i < colCount; i++) {
                tableTitle.add(tblBill.getColumnName(i));
            }
            
            tblModel.setDataVector(data, tableTitle);
        }
        tblBill.setModel(tblModel);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(displaySaleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(displaySaleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(displaySaleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(displaySaleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new displaySaleReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JComboBox<String> cbxDate;
    private javax.swing.JComboBox<String> cbxLanguage;
    private javax.swing.JComboBox<String> cbxUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblsalrep;
    private javax.swing.JTable tblBill;
    // End of variables declaration//GEN-END:variables
}
